import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const fontSans = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(` ${fontSans.className}  `, fontSans.variable)}>
      ;
        {children}
      </body>
    </html>
  );
}
